export interface Store {
  id: number;
  name: string;
  code?: string | null;
  tagline?: string | null;
  promo_text?: string | null;
  address?: string | null;
  phone?: string | null;
  email?: string | null;
  gstin?: string | null;
  fssai?: string | null;
  logo_url?: string | null;
  return_policy?: string | null;
  setup_cost?: number;
  amc?: number;
  is_active: number | boolean;
  upi_id?: string | null;
  upi_name?: string | null;
  receipt_footer?: string | null;
  paper_width?: number | null;
  default_printer?: string | null;
  show_barcode?: number | boolean | null;
  show_upi_qr?: number | boolean | null;
  show_header?: number | boolean | null;
  show_customer?: number | boolean | null;
  show_savings?: number | boolean | null;
  show_tax?: number | boolean | null;
  show_return_policy?: number | boolean | null;
  mandatory_bill_note?: number | boolean | null;
  barcode_printer?: string | null;
  label_width_mm?: number | null;
  label_height_mm?: number | null;
  label_gap_mm?: number | null;
  created_at?: string;
  updated_at?: string;
}

export interface CreateStoreInput {
  name: string;
  code?: string | null;
  tagline?: string | null;
  promo_text?: string | null;
  address?: string | null;
  phone?: string | null;
  email?: string | null;
  gstin?: string | null;
  fssai?: string | null;
  logo_url?: string | null;
  return_policy?: string | null;
  setup_cost?: number;
  amc?: number;
  is_active?: boolean;
  upi_id?: string | null;
  upi_name?: string | null;
  receipt_footer?: string | null;
  paper_width?: number;
  default_printer?: string | null;
  show_barcode?: boolean;
  show_upi_qr?: boolean;
  show_header?: boolean;
  show_customer?: boolean;
  show_savings?: boolean;
  show_tax?: boolean;
  show_return_policy?: boolean;
  mandatory_bill_note?: boolean;
  barcode_printer?: string | null;
  label_width_mm?: number;
  label_height_mm?: number;
  label_gap_mm?: number;
}

export interface UpdateStoreInput {
  name?: string;
  code?: string | null;
  tagline?: string | null;
  promo_text?: string | null;
  address?: string | null;
  phone?: string | null;
  email?: string | null;
  gstin?: string | null;
  fssai?: string | null;
  logo_url?: string | null;
  return_policy?: string | null;
  setup_cost?: number;
  amc?: number;
  is_active?: boolean;
  upi_id?: string | null;
  upi_name?: string | null;
  receipt_footer?: string | null;
  paper_width?: number;
  default_printer?: string | null;
  show_barcode?: boolean;
  show_upi_qr?: boolean;
  show_header?: boolean;
  show_customer?: boolean;
  show_savings?: boolean;
  show_tax?: boolean;
  show_return_policy?: boolean;
  mandatory_bill_note?: boolean;
  barcode_printer?: string | null;
  label_width_mm?: number;
  label_height_mm?: number;
  label_gap_mm?: number;
}
