// Pre-encoded ESC/POS GS v 0 raster bitmap for Retail Sathi Logo
export const RETAIL_SATHI_LOGO_B64 = "HXYwAB4A8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGHgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB+MAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGDwAYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMAwAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQBYAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwDIAGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgCEACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAGEACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAEGADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAECABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAACAMCABAAAAAAAAAAAAAAAAAAAAAAAAAAAAD4HgAAGAICABAAAAAAAAAAAAAAAAAAAAAAAAAAAAMEYYAAEAYCABAAAAAAAAAAAAAAAAAAAAAAAAAAAA8GQIAAMAICABAAAAAAAAAAAAAAAAAAAAAAAAAAABDDgYAAIAQCABAAAAAAAAAAAAAAAAAAAAAAAAAAABBjAIBwIAQDABAAAAAAAAAAAAAAAAAAAAAAAAAAAfAiAoBf6AQCABAAAAAAAAAAAAAAAAAAAAAAAAAAAhwyAQDAf/9Wq9AAAAAAAAAAAAAAAAAAAAAAAAAAAgQTCwCAIEr//vBwAAAAAAAAAAAAAAAAAAAAAAAABAY+DACCYQACAJvgAAAAAAAAAAAAAAAAAAAAAAAABoPgGAGIZCqmqs4wAAAAAAAAAAAAAAAAAAAAAAAAAoNAMAEAcIAWSaygAAAAAAAAAAAAAAAAAAAAAAAAAuIAIAECZFWtJawgAAAAAAAAAAAAAAAAAAAAAAAAAjYAoAMg8Qpcla0wAAAAAAAAAAAAAAAAAAAAAAAAAl0AYAEIJKSdU1SgAAAAAAAAAAAAAAAAAAAAAAAAAQAAQAICglJcq1wwAAAAAAAAAAAAAAAAAAAAAAAAAYABYAJIKSqKS1VgAAAAAAAAAAAAAAAAAAAAAAAAAJAAQAIClUlRJVqgAAAAAAAAAAAAAAAAAAAAAAAAAEAAIAZQSSSql1kgAAAAAAAAAAAAAAAAAAAAAAAAAGAEMAQKpKoSUqywAAAAAAAAAAAAAAAAAAAAAAAAADAMkAaRFSfpS3ogAAAAAAAAAAAAAAAAAAAAAAAAAA44MAQlUppVLpqgAAAAAAAAAAAAAAAAAAAAAAAAAAPgoASfqVgao2pwAAAAAAAAAAAAAAAAAAAAAAAAAACC4ARQZFAMVrqgAAAAAAAAAAAAAAAAAAAAAAAAAAGJoA1gNSAGl1ogAAAAAAAAAAAAAAAAAAAAAAAAAACvcARAGWB1StqwAAAAAAAAAAAAAAAAAAAAAAAAAAB6kA1BVSB2L1qgAAAAAAAAAAAAAAAAAAAAAAAAAAANGAjAyqA1VVqwAAAAAAAAAAAAAAAAAAAAAAAAAAAFTA1A7GB2lrqgAAAAAAAAAAAAAAAAAAAAAAAAAAAGpAiA6rH9Ta+wAAAAAAAAAAAAAAAAAAAAAAAAAAADQwrC2lBqJrrwAAAAAAAAAAAAAAAAAAAAAAAAAAADKY1D9Rg6rtocAAAAAAAAAAAAAAAAAAAAAAAAAAABpMihtK7Uq1qDAAAAAAAAAAAAAAAAAAAAAAAAAAAA0Hqwapf1JrpRwAAAAAAAAAAAAAAAAAAAAAAAAAAAbRpf0lAJVqqIYAAAAAAAAAAAAAAAAAAAAAAAAAAAMqqVaUqqLV1SGAAAAAAAAAAAAAAAAAAAAAAAAAAAGllUilVJVt+pDAAAAAAAAAAAAAAAAAAAAAAAAAAADVolKSIlTXvopgAAAAAAAAAAAAAAAAAAAAAAAAAAB1qpVJVUppq9AwAAAAAAAAAAAAAAAAAAAAAAAAAAA7kkhVJ6V212UYAAAAAAAAAAAAAAAAAAAAAAAAAAANqSVKmJLVq7CIAAAAAAAAAAAAAAAAAAAAAAAAAAADiqog61VrqZ0GgAAAAAAAAAAAAAAAAAAAAAAAAAAApKu/QUltqoxH4AAAAAAAAAAAAAAAAAAAAAAAAAABqn1pAyrVpYcsMAAAAAAAAAAAAAAAAAAAAAAAAAAAkTAADpTq1IG4EAAAAAAAAAAAAAAAAAAAAAAAAAABqrgAfEptq8HgEAAAAAAAAAAAAAAAAAAAAAAAAAAApL//+VLW1ICAHAAAAAAAAAAAAAAAAAAAAAAAAAABkp//6pVrqsGABgAAAAAAAAAAAAAAAAAAAAAAAAAAql+rtFVt1UECAQAAAAAAAAAAAAAAAAAAAAAAAAABko7+8qVq2sEOAYAAAAAAAAAAAAAAAAAAAAAAAAAAqVe3ylTr1WD4AMAAAAAAAAAAAAAAAAAAAAAAAAAApE760pK1aqDQAEAAAAAAAAAAAAAAAAAAAAAAAAAAqqKvSVVu2uBAACAAAAAAAAAAAAAAAAAAAAAAAAAApSkAqkrr7SDAACAAAAAAAAAAAAAAAAAAAAAAAAAA0JX6SVVtVuGAADAAAAAAAAAAAAAAAAAAAAAAAAAAiqSVJSq1+zEAABAAAAAAAAAAAAAAAAAAAAAAAAAA6lKqqqqu1dFAABAAAAAAAAAAAAAAAAAAAAAAAAAAkoqpJKr1drEAABAAAAAAAAAAAAAAAAAAAAAAAAAA1KlUkqU36tkAABgAAAAAAAAAAAAAAAAAAAAAAAAAUlSKqpV6v3mAABAAAAAAAAAAAAAAAAAAAAAAAAAAyopSVVVt6qkAADAAAAAAAAAAAAAAAAAAAAAAAAAAalFJJKq2u62AAGAAAAAAAAAAAAAAAAAAAAAAAAAAVUpVUqq7/XiQAMAAAAAAAAAAAAAAAAAAAAAAAAAAaSqSlVVtb9ThCYAAAAAAAAAAAAAAAAAAAAAAAAAAVVSqVVU79fw8PwAAAAAAAAAAAAAAAAAAAAAAAAAANUqVVVW21q4HYAAAAAAAAAAAAAAAAAAAAAAAAAAAHKlSqqq/qpwBgAAAAAAAAAAAAAAAAAAAAAAAAAAAB1VKVVVV2vAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAepVSqq/VYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD2qtVVbLgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAfVSqqu8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB/aqqvgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAr/9t8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0QX/QAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAowKUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABqgasAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAogaIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABiwVIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0gYoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABggVIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAqgYMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABkwKoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwgKEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABkgMngAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAiwJGwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABogMTwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAkgGHQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABgwFdwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAqQDe4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABggD1uAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAqQHv/gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABgcG9VwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH6+H7/IAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAG/2HursAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHu8B/2kAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAn7sDVfEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH++4Or1MAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMlroKVeIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAaV94ZV0wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAyqus1XdgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAqpb8qqyAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA1W9WqvmAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABurX+1bMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB719abvIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABdfXy1aYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB3t+if+QSIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIt+gGNYwAAiAAAAAAAAAAAAAAAAAAAAAAAAAAACJA3QKsPxgAAASAAAAAAAAAAAAAAAAAAAAAAAAAEQAAQD/wDHBEiAASAAAAAAAAAAAAAAAAAAAAAAAAgAAAO+AAB8AAAIAAAAAAAAAAAAAAAAAAAAAAAAAAABIkDQAAQAEAABEAAAAAAAAAAAAAAAAAAAAAAAAAAIAAgAACAAARJAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH54AAAAAAAAA4AAAAAAAABgAAAAAAAAAAAAAAAAAP/+AAAcAAAAB8AAAAAADgDwAAAAAAAAAAAAAAAAAHufAAAeAAAAD8AA4AAADwHwAAAAAAAAAAAAAAAAAP8HgAA8AAAAB8AD/AAAHgDwAAAAAAAAAAAAAAAAAO4HgAAcAAABjuAH/AAADwHYAEAAAAAAAAAAAAAAAP4GwAA8AAAD58AHHgAAHgDwAfAAAAAAAAAAAAAAAL4DwAAcAAAD98AOPgAADgHwA/AAAAAAAAAAAAAAAP4DwAA8AAAD58AeGgAAHgDwAfAAAAAAAAAAAAAAAPYDw/D/wC6AB0AcHwegf+HwAAAAAAAAAAAAAAAAAP4Dx/D3wHuAB+AcHh3w+6DwAAAAAAAAAAAAAAAAAP4Dxxg8AOHgj8A8Hzg4HgHQAEAAAAAAAAAAAAAAAO4Dzww8AcDh58A8Hjg8HgD4AeAAAAAAAAAAAAAAAP4Dzgw4AcDz5sA8HnA8HAHwAfAAAAAAAAAAAAAAAPwHTwg8AYDx58A0HnA0HgDzwbAAAAAAAAAAAAAAAPYDzhw4AcDz58A8HnAeHAD/4eAAAAAAAAAAAAAAAP4Hn/g4AYDx58A+HDA+HAHYcfAAAAAAAAAAAAAAAPwHj+A8AADzp8AeCAAcHgDweeAAAAAAAAAAAAAAAO4PHgB4AD/b50A/AA/+HADwebAAAAAAAAAAAAAAAPwPHgA4APLx58AbAB1+PADweeAAAAAAAAAAAAAAAP48DgA4GODzx8APwDgaHAzwafAAAAAAAAAAAAAAAP/4GgA4OcDx54AP4Dg+HBzwOaAAAAAAAAAAAAAAAO94Dgw8OcDTxsAD8HAcHhzgeeAAAAAAAAAAAAAAAPzsDww4OcDxx8AA/Dg8HBzweeAAAAAAAAAAAAAAAPx+Dgg8ecDzx8AAHHgcHjzweOAAAAAAAAAAAAAAAPQ/Bxg4MeDhx4AEDDg8HBjQceAAAAAAAAAAAAAAANwfhzA8cMHhxcAPDjh4DjhweMAAAAAAAAAAAAAAAPwPg/Ae4Pfgh4APPB1YD3BgcMAAAAAAAAAAAAAAAHwNgcAPwDzAA8AH+A+4B+AgAAAAAAAAAAAAAAAAAPgHAAAAAACAA4AB4AAQAAAAAAAAAAAAAAAAAAAAAHwAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAOwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAYGCgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAmZCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAASAiAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAUQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQJCgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgKCgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=";

export function getRetailSathiLogoEscPosBytes(): number[] {
  const binary = atob(RETAIL_SATHI_LOGO_B64);
  const bytes = new Array(binary.length);
  for (let i = 0; i < binary.length; i++) {
    bytes[i] = binary.charCodeAt(i);
  }
  return bytes;
}

export async function rasterizeLogoToEscPos(
  imageUrlOrData?: string | null,
  targetWidth = 240
): Promise<number[]> {
  if (
    !imageUrlOrData ||
    imageUrlOrData === "/Retail Sathi.png" ||
    imageUrlOrData.includes("Retail Sathi")
  ) {
    return getRetailSathiLogoEscPosBytes();
  }

  try {
    if (typeof document === "undefined") {
      return getRetailSathiLogoEscPosBytes();
    }

    return new Promise((resolve) => {
      const img = new Image();
      img.crossOrigin = "anonymous";
      img.onload = () => {
        try {
          const width = Math.floor(targetWidth / 8) * 8;
          const height = Math.round(img.height * (width / img.width));
          const canvas = document.createElement("canvas");
          canvas.width = width;
          canvas.height = height;
          const ctx = canvas.getContext("2d");
          if (!ctx) {
            return resolve(getRetailSathiLogoEscPosBytes());
          }

          ctx.fillStyle = "#ffffff";
          ctx.fillRect(0, 0, width, height);
          ctx.drawImage(img, 0, 0, width, height);

          const imgData = ctx.getImageData(0, 0, width, height);
          const pixels = imgData.data;

          const widthBytes = width / 8;
          const xL = widthBytes % 256;
          const xH = Math.floor(widthBytes / 256);
          const yL = height % 256;
          const yH = Math.floor(height / 256);

          const bytes: number[] = [0x1d, 0x76, 0x30, 0x00, xL, xH, yL, yH];

          for (let y = 0; y < height; y++) {
            for (let xb = 0; xb < widthBytes; xb++) {
              let byteVal = 0;
              for (let bit = 0; bit < 8; bit++) {
                const pxIdx = (y * width + (xb * 8 + bit)) * 4;
                const r = pixels[pxIdx];
                const g = pixels[pxIdx + 1];
                const b = pixels[pxIdx + 2];
                const a = pixels[pxIdx + 3];
                const lum = a < 128 ? 255 : r * 0.299 + g * 0.587 + b * 0.114;
                if (lum < 160) {
                  byteVal |= 1 << (7 - bit);
                }
              }
              bytes.push(byteVal);
            }
          }
          resolve(bytes);
        } catch {
          resolve(getRetailSathiLogoEscPosBytes());
        }
      };
      img.onerror = () => {
        resolve(getRetailSathiLogoEscPosBytes());
      };
      img.src = imageUrlOrData;
    });
  } catch {
    return getRetailSathiLogoEscPosBytes();
  }
}
